spring:
  redis:
    cache:
      host: localhost
      port: 6372
      timeout: 300
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: animal
      enable-auto-commit: true
      auto-commit-interval: 1000ms #10초마다 커밋. 기본값 500ms(5초)

      auto-offset-reset: latest
s3:
  domain: https://animal-vote.s3.ap-northeast-2.amazonaws.com
  folder: /animal/